version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./dump:/dump
      - ./zips.json:/zips.json
      - ./import_data.sh:/import_data.sh 
    networks:
      - stack

  metabase:
    image: metabase/metabase:v0.49.0
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - stack
    depends_on:
      - mongodb

# mongodb://mongodb:27017/mongo_database -korsititi ovaj connection string prilikom povezivanja na mongoDB
networks:
  stack:
    driver: bridge
